announce = false
debug = true
description = 'test'
gamemode = 'Freeroam'
host = '0.0.0.0'
language = 'en'
modules = [ 'js-module' ]
name = 'TestServer'
players = 1024
port = 7788
resources = [ 'core', 'BetterNoClip', 'chat' ]
tags = [ 'customTag1', 'customTag2', 'customTag3', 'customTag4' ]
website = 'test.com'
streamingDistance = 1000
# The migration distance for entities
migrationDistance = 1000